name: mikan_flutter
description: mikanani.me

version: 1.0.0-RC1+23

publish_to: none

environment:
  sdk: ">=2.13.0"
  flutter: ">=2.2.1"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.2.0
  firebase_analytics: ^8.1.0
  firebase_crashlytics: ^2.0.4
  path_provider: ^2.0.1
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  dio_http2_adapter: ^2.0.0
  html: ^0.15.0
  provider: ^5.0.0
  oktoast: ^3.0.0
  pull_to_refresh: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  palette_generator: ^0.3.0
  flutter_spinkit: ^5.0.0
  fluentui_system_icons: ^1.1.124
  clipboard: ^0.1.3
  url_launcher: ^6.0.4
  share_plus: ^2.1.2
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_widget_from_html: ^0.6.1
  extended_sliver: ^2.0.0
  extended_image: ^4.1.0
  waterfall_flow: ^3.0.1
  modal_bottom_sheet: ^2.0.0
  jiffy: ^4.1.0
  android_intent_plus: ^1.0.1
  isolate:
    git:
      url: https://github.com/iota9star/isolate
      ref: master
  flutter_colorpicker: ^0.4.0
  connectivity: ^3.0.4
  ff_annotation_route_core: ^2.0.2
  ff_annotation_route_library: ^2.0.1
  sprung: ^3.0.0
  sliver_tools: ^0.2.2

dev_dependencies:
  build_runner: ^2.0.3
  json_serializable: ^4.1.2
  hive_generator: ^1.1.0
  flutter_launcher_icons: ^0.9.0
#  derry: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/mikan.png"


## pub global activate derry
## derry upgrade
#scripts:
#  # derry build
#  build:
#    - flutter pub run build_runner build --delete-conflicting-outputs
#  # derry watch_build
#  watch_build:
#    - flutter pub run build_runner watch --delete-conflicting-outputs
#  # derry ff_route_first
#  ff_route_first:
#    - flutter pub global activate ff_annotation_route
#    - ff_route -s --route-constants --route-helper --route-names --no-is-initial-route --supper-arguments
#  # derry ff_route
#  ff_route: ff_route


